#!/bin/bash --login
#SBATCH --time=40:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=36G
#SBATCH --job-name run_sERRBLUP # rename to get output of each step individually
#SBATCH --output=%x_%j

cd /mnt/home/seguraab/

module purge
module load GCC/9.3.0  OpenMPI/4.0.3  R/4.0.3

TRAITS=( YPACETATE YPDCAFEIN40 YPDHU YPETHANOL YPD14 YPDCAFEIN50 YPDKCL2M YPGALACTOSE YPD40 YPDCHX05 YPDLICL250MM YPGLYCEROL YPD42 YPDCHX1 YPDMV YPRIBOSE YPD6AU YPDCUSO410MM YPDNACL15M YPSORBITOL YPDANISO10 YPDDMSO YPDNACL1M YPXYLOSE YPDANISO20 YPDETOH YPDNYSTATIN YPDANISO50 YPDFLUCONAZOLE YPDSDS YPDBENOMYL200 YPDFORMAMIDE4 YPDSODIUMMETAARSENITE YPDBENOMYL500 YPDFORMAMIDE5 )
MARKERS=(  )
for trait in ${TRAITS[*]}
do
echo "${trait}"
Rscript yeast_sERRBLUP_07232021.R trait 1000 
done

scontrol show job $SLURM_JOB_ID
